### ISSUE TITLE
Not working for me

### ISSUE THREAD

**Issue by c0nt4x** [Bubbleshum/ee_brightbox#2]
I've integrated this as I had a new EE smart hub today but devices aren't being added to the known_devices.yaml even after restarting both router and HA.

Do I need to add the files from these links also?:

Original ee_brightbox component can be found at https://github.com/home-assistant/core/tree/dev/homeassistant/components/ee_brightbox

Extra resources; Krygal's eebrightbox https://github.com/krygal/eebrightbox
Calmjs' Parse https://github.com/calmjs/calmjs.parse

**Comment by Bubbleshum** [comment]
You need to enable adding new devices
new_device_defaults
   track_new_devices: true

**Comment by c0nt4x** [comment]
I have already set that. Is it definitely the admin password that needs entering or should it be the WIFI password?

**Comment by Bubbleshum** [comment]
Definitely the admin password, I have the following

device_tracker:
 - platform: ee_brightbox
   host: 192.168.1.254
   password: [admin password]
   interval_seconds: 8
   consider_home: 60
   new_device_defaults:
     track_new_devices: true

The entities will show up as device_tracker.nameofdevice/macaddress

Only thing I can think is change host, if your IP is different.

If you type in 192.168.1.254 into a Web browser when local and see if it loads your ee hub page

**Comment by c0nt4x** [comment]
Definitely 192.168.1.254 for my router.

I’ve tried my admin password without quotes, with both single and double quotes and it’s still not adding devices into HA.

I’ve definitely got the EE smart hub so I’m at a loss why it’s not working.

**Comment by c0nt4x** [comment]
So, in custom components I have the following file/folder tree:

custom_components
       -ee_brightbox
             -EERouter
             -_init_.py
             -device_tracker.py
             -manifest.json
             -README.md

Is that correct? Or am I missing something?

**Comment by Bubbleshum** [comment]
Have you restarted your home assistant server?

Can you check your notifications, there should be a warning saying your using a custom component for EE_brightbox

**Comment by c0nt4x** [comment]
Hi. Yes restarted server many times but see the below errors:

Logger: homeassistant.loader
Source: loader.py:794
No 'version' key in the manifest file for custom integration 'ee_brightbox'. As of Home Assistant 2021.6, this integration will no longer be loaded. Please report this to the maintainer of 'ee_brightbox'

and

Logger: homeassistant.components.device_tracker
Source: components/device_tracker/legacy.py:260
Integration: Device tracker (documentation, issues)

Error setting up platform legacy ee_brightbox

**Comment by c0nt4x** [comment]
Also got this error now:

Logger: eebrightbox.router.smarthub
Source: /usr/local/lib/python3.8/site-packages/eebrightbox/router/smarthub.py:72
First occurred: 1:44:31 PM (1 occurrences)
Last logged: 1:44:31 PM

Status failed http://192.168.1.254/cgi/cgi_myNetwork.js
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/eebrightbox/router/smarthub.py", line 46, in _request
    response = requests.get(endpoint)
  File "/usr/local/lib/python3.8/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 677, in send
    history = [resp for resp in gen]
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 677, in <listcomp>
    history = [resp for resp in gen]
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 166, in resolve_redirects
    raise TooManyRedirects('Exceeded {} redirects.'.format(self.max_redirects), response=resp)
requests.exceptions.TooManyRedirects: Exceeded 30 redirects.

**Comment by Bubbleshum** [comment]
It looks like there is an issue connecting to the smart hub, do you have inside EErouter the other folders, including calmjs?

Also the error about a version key is just a warning, no need to worry about that for now. Will need to repair it when I have chance.

Is your router the one pictured below?
![smart-hub-HBB-device-640X640-3](https://user-images.githubusercontent.com/68516090/117578914-985c0200-b0e8-11eb-99fe-b2fef67d96bf.jpg)

**Comment by Bubbleshum** [comment]
Also if you try go onto http://192.168.1.254/cgi/cgi_myNetwork.js
Will it show up your devices... it may look a bit of a mess but do your device names shown in the code?

**Comment by c0nt4x** [comment]
Yes I have the other files and a folder inside EERouter. 

When I try that link I get an error saying “can’t open. Too many redirects”

My router is the new white smarthub 
![F3A4BC9D-2529-4B47-AA96-0E7B3A6CCFF7](https://user-images.githubusercontent.com/70321584/117579768-50d77500-b0ec-11eb-9e73-5ea9e0143785.jpeg)

**Comment by Bubbleshum** [comment]
That explains it, your hub is a new one, so it may have another file structure... unfortunately I do not have the new hub, so I am unable to help any further.

Hopefully I can fix this in the future, but until then you will have to try alternate device tracking methods :(

Sorry I can't help.

**Comment by c0nt4x** [comment]
Just for info as an update, I took a chance and added the BT Smarthub integration, knowing that EE and BT are essentially the same company and their hubs are similar, and the integration works with the very latest EE Smarthub.

I have added the below to configuration.yaml and it is adding new devices from my EE Smarthub automatically without issue:

`device_tracker:
- platform: bt_smarthub
  host: 192.168.1.254
  interval_seconds: 8
  consider_home: 60
  new_device_defaults:
  track_new_devices: true`
